spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 201604065704-nruj17vsf4oadkg32dsdcqofp9dj3gft.apps.googleusercontent.com
            client-secret: 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

